
package com.cloud.adapi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.net.URL;

import javax.xml.namespace.QName;

import com.thoughtworks.xstream.core.util.Base64Encoder;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-06-18T17:56:47.259+08:00
 * Generated source version: 3.1.1
 * 
 */
public final class AdapiPortType_Adapi_Client {

    private static final QName SERVICE_NAME = new QName("urn:sangfor:ad:api:soap:v1:base", "adapi");

    private AdapiPortType_Adapi_Client() {
    }
    
    /**
     * https://SANGFOR:8224/api/soap/adapi_server.cgi?wsdl
     * file:/home/adapi.wsdl
     * @param args
     * @throws java.lang.Exception
     */

    public static void main(String args[]) throws java.lang.Exception {
        /*URL wsdlURL = Adapi.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }*/
    	URL adKeystore = Adapi.class.getClassLoader().getResource("META-INF/cloudstack/yx-loadbalancer/ad.keystore");
		if(adKeystore == null || adKeystore.getFile() == null || adKeystore.getFile().equals("")){
			throw new ErrorOpr("Failed to get adKeystore file. " + adKeystore);
		}
		System.setProperty("javax.net.ssl.trustStoreType", "jks");
		System.setProperty("javax.net.ssl.trustStore", adKeystore.getFile());
		System.setProperty("javax.net.ssl.trustStorePassword", "password");
    			
		//URL wsdlURL = new URL("https://SANGFOR:8224/api/soap/adapi_server.cgi?wsdl");
		URL wsdlURL = new URL("file:/home/adapi.wsdl");
        Adapi ss = new Adapi(wsdlURL, SERVICE_NAME);
        AdapiPortType port = ss.getAdapi();
        
        ADAuthType adAuthType = new ADAuthType();
        adAuthType.setPasswd("yxtech123".getBytes());
        adAuthType.setUsername("admin".getBytes());
    	
        {
	    	 //获取ip组test
	    	 System.out.println("Invoking getIpGroupListInfo...");
	         try {
	             IpGroupInfoListType _ipGroupList = port.getIpGroupListInfo(adAuthType);
	             System.out.println("getIpGroupListInfo.result=" + _ipGroupList);
	         } catch (ErrorOpr e) { 
	             System.out.println("Expected exception: errorOpr has occurred.");
	             System.out.println(e.toString());
	         }
	         if(1==1){
	        	 return;
	         }
        }
        
        {
        System.out.println("Invoking deleteNodeMonitor...");
        byte[] _deleteNodeMonitor_monitorName = new byte[0];
        com.cloud.adapi.ADAuthType _deleteNodeMonitor_adAuth = null;
        try {
            com.cloud.adapi.ErrType _deleteNodeMonitor__return = port.deleteNodeMonitor(_deleteNodeMonitor_monitorName, _deleteNodeMonitor_adAuth);
            System.out.println("deleteNodeMonitor.result=" + _deleteNodeMonitor__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deletePersist...");
        byte[] _deletePersist_persistName = new byte[0];
        com.cloud.adapi.ADAuthType _deletePersist_adAuth = null;
        try {
            com.cloud.adapi.ErrType _deletePersist__return = port.deletePersist(_deletePersist_persistName, _deletePersist_adAuth);
            System.out.println("deletePersist.result=" + _deletePersist__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateNodePoolInfo...");
        byte[] _updateNodePoolInfo_nodePoolName = new byte[0];
        com.cloud.adapi.NodePoolViewInfoType _updateNodePoolInfo_nodePoolInfo = null;
        com.cloud.adapi.ADAuthType _updateNodePoolInfo_adAuth = null;
        try {
            com.cloud.adapi.ErrType _updateNodePoolInfo__return = port.updateNodePoolInfo(_updateNodePoolInfo_nodePoolName, _updateNodePoolInfo_nodePoolInfo, _updateNodePoolInfo_adAuth);
            System.out.println("updateNodePoolInfo.result=" + _updateNodePoolInfo__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createVs...");
        com.cloud.adapi.VsCreateInfoType _createVs_vsInfo = null;
        com.cloud.adapi.ADAuthType _createVs_adAuth = null;
        try {
            com.cloud.adapi.ErrType _createVs__return = port.createVs(_createVs_vsInfo, _createVs_adAuth);
            System.out.println("createVs.result=" + _createVs__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteNodePoolInfo...");
        byte[] _deleteNodePoolInfo_nodeName = new byte[0];
        com.cloud.adapi.ADAuthType _deleteNodePoolInfo_adAuth = null;
        try {
            com.cloud.adapi.ErrType _deleteNodePoolInfo__return = port.deleteNodePoolInfo(_deleteNodePoolInfo_nodeName, _deleteNodePoolInfo_adAuth);
            System.out.println("deleteNodePoolInfo.result=" + _deleteNodePoolInfo__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getNodeMonitorInfo...");
        com.cloud.adapi.ADAuthType _getNodeMonitorInfo_adAuth = null;
        byte[] _getNodeMonitorInfo_monitorName = new byte[0];
        try {
            com.cloud.adapi.NodeMonitorInfoType _getNodeMonitorInfo__return = port.getNodeMonitorInfo(_getNodeMonitorInfo_adAuth, _getNodeMonitorInfo_monitorName);
            System.out.println("getNodeMonitorInfo.result=" + _getNodeMonitorInfo__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updatePersist...");
        byte[] _updatePersist_persistName = new byte[0];
        com.cloud.adapi.PersistUpdateInfoType _updatePersist_persistInfo = null;
        com.cloud.adapi.ADAuthType _updatePersist_adAuth = null;
        try {
            com.cloud.adapi.ErrType _updatePersist__return = port.updatePersist(_updatePersist_persistName, _updatePersist_persistInfo, _updatePersist_adAuth);
            System.out.println("updatePersist.result=" + _updatePersist__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteSched...");
        byte[] _deleteSched_vsName = new byte[0];
        byte[] _deleteSched_schedInfo = new byte[0];
        com.cloud.adapi.ADAuthType _deleteSched_adAuth = null;
        try {
            com.cloud.adapi.ErrType _deleteSched__return = port.deleteSched(_deleteSched_vsName, _deleteSched_schedInfo, _deleteSched_adAuth);
            System.out.println("deleteSched.result=" + _deleteSched__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteNode...");
        com.cloud.adapi.NodeKeyExtType _deleteNode_nodeKey = null;
        com.cloud.adapi.ADAuthType _deleteNode_adAuth = null;
        try {
            com.cloud.adapi.ErrType _deleteNode__return = port.deleteNode(_deleteNode_nodeKey, _deleteNode_adAuth);
            System.out.println("deleteNode.result=" + _deleteNode__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteIpGroup...");
        byte[] _deleteIpGroup_ipGroupName = new byte[0];
        com.cloud.adapi.ADAuthType _deleteIpGroup_adAuth = null;
        try {
            com.cloud.adapi.ErrType _deleteIpGroup__return = port.deleteIpGroup(_deleteIpGroup_ipGroupName, _deleteIpGroup_adAuth);
            System.out.println("deleteIpGroup.result=" + _deleteIpGroup__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getSnatInfoList...");
        com.cloud.adapi.ADAuthType _getSnatInfoList_adAuth = null;
        try {
            com.cloud.adapi.SnatInfoListType _getSnatInfoList__return = port.getSnatInfoList(_getSnatInfoList_adAuth);
            System.out.println("getSnatInfoList.result=" + _getSnatInfoList__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getPersistInfoList...");
        com.cloud.adapi.ADAuthType _getPersistInfoList_adAuth = null;
        try {
            com.cloud.adapi.PersistInfoListType _getPersistInfoList__return = port.getPersistInfoList(_getPersistInfoList_adAuth);
            System.out.println("getPersistInfoList.result=" + _getPersistInfoList__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createServ...");
        com.cloud.adapi.ServiceInfoType _createServ_serverInfo = null;
        com.cloud.adapi.ADAuthType _createServ_adAuth = null;
        try {
            com.cloud.adapi.ErrType _createServ__return = port.createServ(_createServ_serverInfo, _createServ_adAuth);
            System.out.println("createServ.result=" + _createServ__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getIpGroupListInfo...");
        com.cloud.adapi.ADAuthType _getIpGroupListInfo_adAuth = null;
        try {
            com.cloud.adapi.IpGroupInfoListType _getIpGroupListInfo__return = port.getIpGroupListInfo(_getIpGroupListInfo_adAuth);
            System.out.println("getIpGroupListInfo.result=" + _getIpGroupListInfo__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateVs...");
        byte[] _updateVs_vsName = new byte[0];
        com.cloud.adapi.VsUpdateInfoType _updateVs_vsInfo = null;
        com.cloud.adapi.ADAuthType _updateVs_adAuth = null;
        try {
            com.cloud.adapi.ErrType _updateVs__return = port.updateVs(_updateVs_vsName, _updateVs_vsInfo, _updateVs_adAuth);
            System.out.println("updateVs.result=" + _updateVs__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking addServPortInfo...");
        com.cloud.adapi.ADAuthType _addServPortInfo_adAuth = null;
        byte[] _addServPortInfo_serverName = new byte[0];
        com.cloud.adapi.PortScopeType _addServPortInfo_portInfo = null;
        try {
            com.cloud.adapi.ErrType _addServPortInfo__return = port.addServPortInfo(_addServPortInfo_adAuth, _addServPortInfo_serverName, _addServPortInfo_portInfo);
            System.out.println("addServPortInfo.result=" + _addServPortInfo__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getNodePoolList...");
        com.cloud.adapi.ADAuthType _getNodePoolList_adAuth = null;
        try {
            com.cloud.adapi.NodePoolListType _getNodePoolList__return = port.getNodePoolList(_getNodePoolList_adAuth);
            System.out.println("getNodePoolList.result=" + _getNodePoolList__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getVsStatus...");
        com.cloud.adapi.ADAuthType _getVsStatus_adAuth = null;
        try {
            com.cloud.adapi.VsStatusListType _getVsStatus__return = port.getVsStatus(_getVsStatus_adAuth);
            System.out.println("getVsStatus.result=" + _getVsStatus__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateNodeMonitor...");
        byte[] _updateNodeMonitor_monitorName = new byte[0];
        com.cloud.adapi.NodeMonitorUpdateInfoType _updateNodeMonitor_monitorInfo = null;
        com.cloud.adapi.ADAuthType _updateNodeMonitor_adAuth = null;
        try {
            com.cloud.adapi.ErrType _updateNodeMonitor__return = port.updateNodeMonitor(_updateNodeMonitor_monitorName, _updateNodeMonitor_monitorInfo, _updateNodeMonitor_adAuth);
            System.out.println("updateNodeMonitor.result=" + _updateNodeMonitor__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createNodeMonitor...");
        com.cloud.adapi.NodeMonitorInfoType _createNodeMonitor_monitorInfo = null;
        com.cloud.adapi.ADAuthType _createNodeMonitor_adAuth = null;
        try {
            com.cloud.adapi.ErrType _createNodeMonitor__return = port.createNodeMonitor(_createNodeMonitor_monitorInfo, _createNodeMonitor_adAuth);
            System.out.println("createNodeMonitor.result=" + _createNodeMonitor__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getVsBaseInfoList...");
        com.cloud.adapi.ADAuthType _getVsBaseInfoList_adAuth = null;
        try {
            com.cloud.adapi.VsBaseInfoListType _getVsBaseInfoList__return = port.getVsBaseInfoList(_getVsBaseInfoList_adAuth);
            System.out.println("getVsBaseInfoList.result=" + _getVsBaseInfoList__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getNodeMonitorInfoList...");
        com.cloud.adapi.ADAuthType _getNodeMonitorInfoList_adAuth = null;
        try {
            com.cloud.adapi.NodeMonitorInfoListType _getNodeMonitorInfoList__return = port.getNodeMonitorInfoList(_getNodeMonitorInfoList_adAuth);
            System.out.println("getNodeMonitorInfoList.result=" + _getNodeMonitorInfoList__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createPersist...");
        com.cloud.adapi.PersistInfoType _createPersist_persistInfo = null;
        com.cloud.adapi.ADAuthType _createPersist_adAuth = null;
        try {
            com.cloud.adapi.ErrType _createPersist__return = port.createPersist(_createPersist_persistInfo, _createPersist_adAuth);
            System.out.println("createPersist.result=" + _createPersist__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getSslProfileList...");
        com.cloud.adapi.ADAuthType _getSslProfileList_adAuth = null;
        try {
            com.cloud.adapi.SslProfileListType _getSslProfileList__return = port.getSslProfileList(_getSslProfileList_adAuth);
            System.out.println("getSslProfileList.result=" + _getSslProfileList__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getNodeStatus...");
        byte[] _getNodeStatus_nodePoolName = new byte[0];
        com.cloud.adapi.ADAuthType _getNodeStatus_adAuth = null;
        try {
            com.cloud.adapi.NodeStatusListType _getNodeStatus__return = port.getNodeStatus(_getNodeStatus_nodePoolName, _getNodeStatus_adAuth);
            System.out.println("getNodeStatus.result=" + _getNodeStatus__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getNodeList...");
        com.cloud.adapi.ADAuthType _getNodeList_adAuth = null;
        byte[] _getNodeList_nodePoolName = new byte[0];
        try {
            com.cloud.adapi.NodeListType _getNodeList__return = port.getNodeList(_getNodeList_adAuth, _getNodeList_nodePoolName);
            System.out.println("getNodeList.result=" + _getNodeList__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createIpGroup...");
        com.cloud.adapi.IpGroupInfoType _createIpGroup_ipGroupInfo = null;
        com.cloud.adapi.ADAuthType _createIpGroup_adAuth = null;
        try {
            com.cloud.adapi.ErrType _createIpGroup__return = port.createIpGroup(_createIpGroup_ipGroupInfo, _createIpGroup_adAuth);
            System.out.println("createIpGroup.result=" + _createIpGroup__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getWanNameInfo...");
        com.cloud.adapi.ADAuthType _getWanNameInfo_adAuth = null;
        try {
            com.cloud.adapi.WanInfoListType _getWanNameInfo__return = port.getWanNameInfo(_getWanNameInfo_adAuth);
            System.out.println("getWanNameInfo.result=" + _getWanNameInfo__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getVsSchedList...");
        com.cloud.adapi.ADAuthType _getVsSchedList_adAuth = null;
        try {
            com.cloud.adapi.VsSchedListType _getVsSchedList__return = port.getVsSchedList(_getVsSchedList_adAuth);
            System.out.println("getVsSchedList.result=" + _getVsSchedList__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateNode...");
        com.cloud.adapi.NodeKeyType _updateNode_nodeKey = null;
        com.cloud.adapi.NodeInfoExType _updateNode_nodeInfo = null;
        com.cloud.adapi.ADAuthType _updateNode_adAuth = null;
        try {
            com.cloud.adapi.ErrType _updateNode__return = port.updateNode(_updateNode_nodeKey, _updateNode_nodeInfo, _updateNode_adAuth);
            System.out.println("updateNode.result=" + _updateNode__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getServPortInfo...");
        com.cloud.adapi.ADAuthType _getServPortInfo_adAuth = null;
        byte[] _getServPortInfo_serverName = new byte[0];
        try {
            com.cloud.adapi.PortListType _getServPortInfo__return = port.getServPortInfo(_getServPortInfo_adAuth, _getServPortInfo_serverName);
            System.out.println("getServPortInfo.result=" + _getServPortInfo__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createNodePoolInfo...");
        com.cloud.adapi.NodePoolCreateInfoType _createNodePoolInfo_nodePoolInfo = null;
        com.cloud.adapi.ADAuthType _createNodePoolInfo_adAuth = null;
        try {
            com.cloud.adapi.ErrType _createNodePoolInfo__return = port.createNodePoolInfo(_createNodePoolInfo_nodePoolInfo, _createNodePoolInfo_adAuth);
            System.out.println("createNodePoolInfo.result=" + _createNodePoolInfo__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getWanIpInfoList...");
        com.cloud.adapi.ADAuthType _getWanIpInfoList_adAuth = null;
        byte[] _getWanIpInfoList_name = new byte[0];
        try {
            com.cloud.adapi.WanIpListType _getWanIpInfoList__return = port.getWanIpInfoList(_getWanIpInfoList_adAuth, _getWanIpInfoList_name);
            System.out.println("getWanIpInfoList.result=" + _getWanIpInfoList__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteServ...");
        byte[] _deleteServ_serverName = new byte[0];
        com.cloud.adapi.ADAuthType _deleteServ_adAuth = null;
        try {
            com.cloud.adapi.ErrType _deleteServ__return = port.deleteServ(_deleteServ_serverName, _deleteServ_adAuth);
            System.out.println("deleteServ.result=" + _deleteServ__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteServPortInfo...");
        com.cloud.adapi.ADAuthType _deleteServPortInfo_adAuth = null;
        byte[] _deleteServPortInfo_serverName = new byte[0];
        com.cloud.adapi.PortScopeType _deleteServPortInfo_portInfo = null;
        try {
            com.cloud.adapi.ErrType _deleteServPortInfo__return = port.deleteServPortInfo(_deleteServPortInfo_adAuth, _deleteServPortInfo_serverName, _deleteServPortInfo_portInfo);
            System.out.println("deleteServPortInfo.result=" + _deleteServPortInfo__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createNode...");
        byte[] _createNode_nodePoolName = new byte[0];
        com.cloud.adapi.NodeInfoType _createNode_nodeInfo = null;
        com.cloud.adapi.ADAuthType _createNode_adAuth = null;
        try {
            com.cloud.adapi.ErrType _createNode__return = port.createNode(_createNode_nodePoolName, _createNode_nodeInfo, _createNode_adAuth);
            System.out.println("createNode.result=" + _createNode__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getPersistInfo...");
        com.cloud.adapi.ADAuthType _getPersistInfo_adAuth = null;
        byte[] _getPersistInfo_persistName = new byte[0];
        try {
            com.cloud.adapi.PersistInfoType _getPersistInfo__return = port.getPersistInfo(_getPersistInfo_adAuth, _getPersistInfo_persistName);
            System.out.println("getPersistInfo.result=" + _getPersistInfo__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getServInfoList...");
        com.cloud.adapi.ADAuthType _getServInfoList_adAuth = null;
        try {
            com.cloud.adapi.ServiceInfoListType _getServInfoList__return = port.getServInfoList(_getServInfoList_adAuth);
            System.out.println("getServInfoList.result=" + _getServInfoList__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateServ...");
        byte[] _updateServ_serverName = new byte[0];
        com.cloud.adapi.ServerInfoExType _updateServ_serverInfo = null;
        com.cloud.adapi.ADAuthType _updateServ_adAuth = null;
        try {
            com.cloud.adapi.ErrType _updateServ__return = port.updateServ(_updateServ_serverName, _updateServ_serverInfo, _updateServ_adAuth);
            System.out.println("updateServ.result=" + _updateServ__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getNodeInfo...");
        com.cloud.adapi.ADAuthType _getNodeInfo_adAuth = null;
        com.cloud.adapi.NodeKeyType _getNodeInfo_nodeKey = null;
        try {
            com.cloud.adapi.NodeInfoType _getNodeInfo__return = port.getNodeInfo(_getNodeInfo_adAuth, _getNodeInfo_nodeKey);
            System.out.println("getNodeInfo.result=" + _getNodeInfo__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteIpInfo...");
        com.cloud.adapi.ADAuthType _deleteIpInfo_adAuth = null;
        byte[] _deleteIpInfo_ipGroupName = new byte[0];
        com.cloud.adapi.IpInfoType _deleteIpInfo_ipInfo = null;
        try {
            com.cloud.adapi.ErrType _deleteIpInfo__return = port.deleteIpInfo(_deleteIpInfo_adAuth, _deleteIpInfo_ipGroupName, _deleteIpInfo_ipInfo);
            System.out.println("deleteIpInfo.result=" + _deleteIpInfo__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getVsInfo...");
        com.cloud.adapi.ADAuthType _getVsInfo_adAuth = null;
        byte[] _getVsInfo_vsName = new byte[0];
        try {
            com.cloud.adapi.VsViewInfoType _getVsInfo__return = port.getVsInfo(_getVsInfo_adAuth, _getVsInfo_vsName);
            System.out.println("getVsInfo.result=" + _getVsInfo__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateIpGroup...");
        byte[] _updateIpGroup_ipGroupName = new byte[0];
        com.cloud.adapi.IpGroupBaseType _updateIpGroup_ipGroupInfo = null;
        com.cloud.adapi.ADAuthType _updateIpGroup_adAuth = null;
        try {
            com.cloud.adapi.ErrType _updateIpGroup__return = port.updateIpGroup(_updateIpGroup_ipGroupName, _updateIpGroup_ipGroupInfo, _updateIpGroup_adAuth);
            System.out.println("updateIpGroup.result=" + _updateIpGroup__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteVs...");
        byte[] _deleteVs_vsName = new byte[0];
        com.cloud.adapi.ADAuthType _deleteVs_adAuth = null;
        try {
            com.cloud.adapi.ErrType _deleteVs__return = port.deleteVs(_deleteVs_vsName, _deleteVs_adAuth);
            System.out.println("deleteVs.result=" + _deleteVs__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getNodePoolInfo...");
        com.cloud.adapi.ADAuthType _getNodePoolInfo_adAuth = null;
        byte[] _getNodePoolInfo_nodePoolName = new byte[0];
        try {
            com.cloud.adapi.NodePoolViewInfoType _getNodePoolInfo__return = port.getNodePoolInfo(_getNodePoolInfo_adAuth, _getNodePoolInfo_nodePoolName);
            System.out.println("getNodePoolInfo.result=" + _getNodePoolInfo__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getIpInfoList...");
        com.cloud.adapi.ADAuthType _getIpInfoList_adAuth = null;
        byte[] _getIpInfoList_ipGroupName = new byte[0];
        try {
            com.cloud.adapi.IpInfoListType _getIpInfoList__return = port.getIpInfoList(_getIpInfoList_adAuth, _getIpInfoList_ipGroupName);
            System.out.println("getIpInfoList.result=" + _getIpInfoList__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking addIpInfoList...");
        com.cloud.adapi.ADAuthType _addIpInfoList_adAuth = null;
        byte[] _addIpInfoList_ipGroupName = new byte[0];
        com.cloud.adapi.IpInfoType _addIpInfoList_ipInfo = null;
        try {
            com.cloud.adapi.ErrType _addIpInfoList__return = port.addIpInfoList(_addIpInfoList_adAuth, _addIpInfoList_ipGroupName, _addIpInfoList_ipInfo);
            System.out.println("addIpInfoList.result=" + _addIpInfoList__return);

        } catch (ErrorOpr e) { 
            System.out.println("Expected exception: errorOpr has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
