
package com.cloud.adapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-06-18T17:56:47.371+08:00
 * Generated source version: 3.1.1
 */

@WebFault(name = "error", targetNamespace = "urn:sangfor:ad:api:soap:v1:base")
public class ErrorOpr extends Exception {
    
    private com.cloud.adapi.ErrInfoType error;

    public ErrorOpr() {
        super();
    }
    
    public ErrorOpr(String message) {
        super(message);
    }
    
    public ErrorOpr(String message, Throwable cause) {
        super(message, cause);
    }

    public ErrorOpr(String message, com.cloud.adapi.ErrInfoType error) {
        super(message);
        this.error = error;
    }

    public ErrorOpr(String message, com.cloud.adapi.ErrInfoType error, Throwable cause) {
        super(message, cause);
        this.error = error;
    }

    public com.cloud.adapi.ErrInfoType getFaultInfo() {
        return this.error;
    }
}
